[package]
name = "fofa-dorker"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.9"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.41.1", features = ["full"] }
serde_json = "1.0"
base64 = "0.22.1"
futures = "0.3.31"
